# Permalinks
permalink:           pretty

# Setup
title:               LeeRyan Solomon
tagline:             A Modest Data Science Blog
url:                 http://guesswhat91.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              LeeRyan Solomon
  url:
  email:             leeryansolomon01@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/guesswhat91

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
